### ISSUE TITLE
after you prepare your models?

### ISSUE THREAD

**Issue by devOMAR-2** [tomatophp/filament-invoices#3]
I installed the plugin right away and did what the "docs" says:

- I've registered `for` and `from` in the boot function.

Everything works as expected, but when I want to view a invoice. This happens:

`Call to undefined method App\Models\Client::locations()` What is locations? why is it required? what if my model don't have "locations"?

![Error Screenshot](https://github.com/user-attachments/assets/8a913d66-2522-4e30-987d-667182050385)

**Comment by 3x1io** [comment]
okay if you use our plugin `filament-location` you will find a locations table inside it, to save an address for your customer, you can add it to your model, and I will handle a trait for it inside the package

**Comment by 3x1io** [comment]
or you can create a `locations` table like this schema

```php
  $table->id();

  $table->string('street');
  $table->foreignId('area_id')->nullable()->constrained('areas')->onDelete('cascade');
  $table->foreignId('city_id')->nullable()->constrained('cities')->onDelete('cascade');
  $table->foreignId('country_id')->nullable()->constrained('countries')->onDelete('cascade');
  $table->unsignedInteger('home_number')->nullable();
  $table->unsignedInteger('flat_number')->nullable();
  $table->unsignedInteger('floor_number')->nullable();
  $table->string('mark')->nullable();
  $table->text('map_url')->nullable();
  $table->string('note')->nullable();
  $table->string('lat')->nullable();
  $table->string('lng')->nullable();
  $table->string('zip')->nullable();
  $table->boolean('is_main')->default(0)->nullable();
  $table->timestamps();
```

 and Model then create a locations() method on your model to make this work because it takes the address info of the customer from this relation.
