### ISSUE TITLE
During Installation

### ISSUE THREAD

**Issue by himadreekuntal** [tomatophp/filament-invoices#5]
Getting following message after running the command "php artisan filament-invoices:install"

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'example_app.types' doesn't exist (Connection: mysql, SQL: select * from `types` where `for` = invoices and `type` = status and `key` = draft limit 1)

**Comment by 3x1io** [comment]
just make sure that [filament-types](https://www.github.com/tomatophp/filament-types) is installed, and we will allow it on the `composer.json`
