### ISSUE TITLE
could not find driver (Connection: , SQL: select "label", "name" from "icons" limit 10) 

### ISSUE THREAD

**Issue by mallemagassa** [tomatophp/filament-invoices#6]
I installed tomatophp/filament-invoices. When I tried to access http://127.0.0.1:8000/admin/invoice-status, I received the error: 'could not find driver (Connection: , SQL: select "label", "name" from "icons" limit 10)'. Thank you for your response."

**Comment by 3x1io** [comment]
please allow SQLite3 PHP ex for caching.

**Comment by mallemagassa** [comment]
Thank you for your response, it solved my problem. I loved your package. Is it possible to become a contributor?

**Comment by mallemagassa** [comment]
> please allow SQLite3 PHP ex for caching.

Thank you for your response, it solved my problem. I loved your package. Is it possible to become a contributor?

**Comment by 3x1io** [comment]
hi @mallemagassa, that's great, feel free to open any PR for what you want and I will review it and if it's okay I will add it. and you start as a contributor when you just report a problem

**Comment by mallemagassa** [comment]
> hi @mallemagassa, that's great, feel free to open any PR for what you want and I will review it and if it's okay I will add it. and you start as a contributor when you just report a problem

Thank you very much!

**Comment by mallemagassa** [comment]
I received another problem. I'm using the filament-type plugin, and when I click on an icon, it shows me this error SQLSTATE[42S02]: Base table or view not found: 1146 Table 'invoices.media' doesn't exist (Connection: mysql, SQL: select * from `media` where `media`.`model_id` in (1) and `media`.`model_type` = TomatoPHP\FilamentTypes\Models\Type) .
